name: Run Gradle on PRs
on:
  push:
    branches: [ feat-scripts-added ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: false
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/feat-scripts-added' }}

      - name: Execute Gradle build
        run: ./scripts/build.sh
